### ISSUE TITLE
Сделать дистрибутив для запуска Drupal 8.

### ISSUE THREAD

**Issue by dstorozhuk** [drupal-ukraine/panels#13]
Возможные варианты 
https://hub.docker.com/_/drupal/
https://github.com/wodby/docker4drupal
Vagrand build by @podarok

**Comment by dstorozhuk** [comment]
Travis для билдов? чисто чтобы поэкспериментировать если будет время

**Comment by pazhyn** [comment]
http://docksal.io такой инструмент рассматривали? есть ли реальный опыт с ним?

**Comment by dstorozhuk** [comment]
Не насматривал. Опиши коротко пож чем может быть полезен.

**Comment by pazhyn** [comment]
Еще не пробовал. Хочу попробовать работать с Docker. И хочется найти наиболее простой и удобный способ.

**Comment by dstorozhuk** [comment]
@podarok , я пока эту задачу направляю на @semjuel . Он уже начал делать дистрибутив для себя на базе докера, что предпочтительно в силу мейнстрима 😄 .
Если  дистрибутив будет работать ОК - заюзаем его для всего проекта.

**Comment by dstorozhuk** [comment]
Done
